import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Marquee from 'react-fast-marquee';
import Showtimes from '../components/showtimes'

const matineeImg = '/blackpanther-matinee.jpg';



export default function Home() {

  return (

    <div className="border-10 bg-black flex flex-col items-center justify-between align-middle h-screen w-screen border-blue-500 ">
      <Head>
        <title>Welcome to Gardena Cinema</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>

      <header>
        <Marquee className="bg-yellow-300 text-4xl pt-3 pb-4" gradient={false} speed={100} direction="left"><span className={styles.marquee}>. . . . . . . . . . <span className="text-2xl hover:text-white hover:cursor-pointer">INFO</span> . . . . . . . . . . . . . . . . .www.gardenacinema.com . . . . . . . . . . . . . . . <span className="text-2xl hover:text-white hover:cursor-pointer">ABOUT</span> . . . . . . . . . . . . www.gardenacinema.com . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . www.gardenacinema.com</span></Marquee>
      </header>
      <main className="text-cyan-300  h-full w-full flex flex-row overflow-y-auto justify-center items-center border-green-500">
        
        <div className="border-green-500" style={{width: '600px'}}>
          <Image src={matineeImg} alt="Gardena Cinema Marquee" height={900} width={600}/>
        </div>
        <div className="ml-4 w-1/2 h-[500px] flex flex-col self-start">
          <div className={styles.showtimes}>
            Showtimes
          </div>
          <div className="overflow-y-auto">
            <Showtimes/>
          </div>
        </div>
        
          {/* <div className="border border-green-500 h-96 top-1/2 w-96">
            who
          </div> */}

      </main>
      <footer className="flex flex-row justify-between w-full border-black border-1">
      <Marquee className="bg-yellow-300 text-4xl pt-3 pb-4" gradient={false} speed={100} direction="right"><span className={styles.marquee}>. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .www.gardenacinema.com . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . www.gardenacinema.com . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . www.gardenacinema.com</span></Marquee>
        {/* <div className="w-1/5 h-full">

      <header className={styles.main}>
        <div className="border border-black text-3xl flex w-screen justify-between">
          <div className="text-8xl">GARDENA CINEMA</div>
          <div className="w-1/3 flex flex-col justify-end">
            <div className="flex flex-row justify-between"><span>HOME</span><span>EVENTS</span><span>CONTACT</span></div>
          </div>
        </div>
      </header>
      <main className="h-full w-full flex items-center flex-col justify-center border-8 overflow-y-scroll">
        <div className="border border-green-500 h-2/4 w-96 ">
          
        </div>
        <div className="border border-red-500 h-96 w-96">

        </div>
        <div className="border border-purple-500 h-96 w-96">

        </div>

      </main>
      <footer className="flex flex-row justify-between w-full border border-b-8">
        <div className="w-1/5 h-full">
>>>>>>> Stashed changes
          <p>ig</p><p>fb</p><p>twt</p>
        </div>
        <div className="w-2/5 h-full flex flex-col justify-end text-right">
          <div>
            555-573-9087
          </div>
          <div>
            127 Crenshaw Ave., Gardena, CA 90406
          </div>
        </div>
        </div> */}
      </footer>
    </div>
  )
}